version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:

      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - checkout
      - run:
          command: ./gradlew build
